services:
  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432

volumes:
  db-data: